CREATE DATABASE GESTOR;

USE GESTOR;



CREATE TABLE LIBROS (
    ID_LIBRO INT(11) NOT NULL AUTO_INCREMENT,
    NOMBRE_LIBRO VARCHAR(255) NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
    FECHA_LANZAMIENTO VARCHAR(255) NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_LIBRO));



CREATE TABLE PRESTAMOS (
    ID_PRESTAMO INT(11) NOT NULL AUTO_INCREMENT,
    ID_LIBRO INT(11) DEFAULT NULL,
    ID_USUARIO INT(11) DEFAULT NULL,
    FECHA_PRESTAMO DATE DEFAULT NULL,
    FECHA_DEVOLUCION DATE DEFAULT NULL,
    PRIMARY KEY (ID_PRESTAMO),
    KEY FK_LIBRO (ID_LIBRO),
    KEY FK_USUARIO (ID_USUARIO),
    CONSTRAINT FK_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS (ID_LIBRO),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO));




CREATE TABLE USUARIOS (
    ID_USUARIO INT(11) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    DNI VARCHAR(8) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    UNIQUE KEY DNI (DNI));



INSERT INTO LIBROS (ID_LIBRO, NOMBRE_LIBRO, AUTOR, FECHA_LANZAMIENTO, GENERO)
VALUES
(1, 'LAS AVENTURAS Y DESVENTURAS DE CASIPIERRO DEL HAMBRE', 'GRACIELA MONTES', 1995, 'FICCION'),
(2, 'EN LLAMAS', 'SUZANNE COLLINS', 2009, 'CIENCIA FICCION'),
(3, 'LOS JUEGOS DEL HAMBRE', 'SUZANNE COLLINS', 2008, 'FICCION'),
(4, 'DUNE', 'FRANK HEBERT', 1965, 'CIENCIA FICCION'),
(5, 'SAW', 'BENJAMIN POOLE', 2011, 'TERROR');


INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDO, DNI, TELEFONO, EMAIL)
VALUES
(1, 'TOBIAS', 'PEREZ', '46495650', '03482646470', 'TOBIASJOSEPEREZ@GMAIL.COM'),
(2, 'FRANCISCO', 'FRANCO', '46965034', '03482508700', 'FRANCISCOFRANCO@GMAIL.COM'),
(3, 'FEDERICO', 'MALFASI', '42378456', '03482955996', 'FEDERICOMALFASI@GMAIL.COM'),
(4, 'TOMAS', 'LEDESMA', '45789065', '03482456578', 'TOMASLEDESMA@GMAIL.COM'),
(5, 'JULIAN', 'RODRIGUEZ', '46034945', '03482465378', 'JULIANRO@GMAIL.COM');



INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FECHA_PRESTAMO, FECHA_DEVOLUCION)
VALUES
(1, 1, 1, '2022-04-12', NULL),
(2, 2, 2, '2023-05-16', NULL),
(3, 3, 3, '2024-06-24', NULL);


SELECT * FROM LIBROS
WHERE GENERO="FICCION";

SELECT * FROM LIBROS
WHERE AUTOR="SUZANNE COLLINS";


SELECT * FROM USUARIOS
WHERE ID_USUARIO="3";

SELECT * FROM USUARIOS
WHERE APELLIDO="PEREZ";

SELECT P.ID_PRESTAMO, L.ID_LIBRO, P.ID_USUARIO, P.FECHA_PRESTAMO, P.FECHA_DEVOLUCION 
FROM PRESTAMOS P
JOIN LIBROS L ON P.ID_LIBRO = L.ID_LIBRO
JOIN USUARIOS U ON P.ID_USUARIO = U.ID_USUARIO
WHERE P.FECHA_DEVOLUCION IS NULL;

SELECT COUNT (*) AS LIBROS_PRESTADOS
FROM PRESTAMOS
WHERE FECHA_DEVOLUCION IS NULL;




